#!/bin/bash
set -e

#SEARCH_ENGINE='https://www.google.com/search?q='
SEARCH_ENGINE='https://duckduckgo.com/?q='

if which urlencode > /dev/null ; then
    ENCODED=`echo $@ | urlencode`
    lynx "$SEARCH_ENGINE$ENCODED"
else
    cargo install urlencode || echo 'install `cargo` or `urlencode` please'; exit 1
fi

