#!/bin/bash

#
# Initialize my custom environment for a new UNIX-like system.
# 
# To use:
# 
#     $ cd ~
#     $ git clone https://github.com/eignnx/dotfiles
#     $ cd dotfiles
#     $ bash INITIALIZE
#

set -e

################################################################################
# Vim
################################################################################

# Create symlink in $HOME to `.vimrc`
ln -s ../dotfiles/.vimrc $HOME/.vimrc


################################################################################
# Rust
################################################################################

echo 'INITIALIZE > Rust'
echo 'INITIALIZE > Rust > `rustup` : installing...'
# Install rustup with `default` profile which `component add`s:
#     - rustc
#     - rust-std
#     - cargo
#     - rust-docs
#     - rustfmt
#     - clippy
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

echo 'INITIALIZE > Rust > `rls` : installing...'
rustup component add rls # Install the rust language server


################################################################################
# Utils
################################################################################

echo 'INITIALIZE > Utils > `urlencode` : installing...'
cargo install urlencode

echo 'INITIALIZE > Utils > `exa` : installing...'
cargo install exa


################################################################################
# Prolog
################################################################################

echo 'INITIALIZE > Prolog'

echo 'INITIALIZE > Prolog > SWI'
read -p 'Install SWI Prolog? '
if [[ $REPLY ~= 'y|Y|yes|Yes|' ]]; then
    echo 'INITIALIZE > Prolog > SWI : installing...'

    # Add the package repository for `apt`.
    sudo apt-get install software-properties-common
    sudo apt-add-repository ppa:swi-prolog/stable
    sudo apt-get update
    sudo apt-get install swi-prolog
fi

echo 'INITIALIZE > Prolog > Scryer'
read -p 'Install `scryer-prolog`? '
if [[ $REPLY ~= 'y|Y|yes|Yes|' ]]; then
    echo 'INITIALIZE > Prolog > `scryer-prolog` : installing...'
    cargo install scryer-prolog \
        || echo 'INITIALIZE: Problem - Could not install `scryer-prolog`. It happens.'
fi


################################################################################
# Moving Config Files
################################################################################

# Create symlink in $HOME to `.vimrc`
ln -s ../dotfiles/.bashrc       $HOME/.bashrc
ln -s ../dotfiles/.bash_aliases $HOME/.bash_aliases
ln -s ../dotfiles/.lynxrc       $HOME/.lynxrc


################################################################################

echo "INITIALIZE: You're all set up!"

